(() => {
  'use strict';
  const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
  let visitorPage = 1;

  async function api(path, options = {}) {
    const response = await fetch(path, { credentials: 'same-origin', ...options });
    const type = response.headers.get('content-type') || '';
    const data = type.includes('application/json') ? await response.json() : null;
    if (!response.ok) {
      if (response.status === 401 || response.status === 403) throw new Error('Session expired or access denied');
      throw new Error(data?.error || `Request failed (${response.status})`);
    }
    if (!data) throw new Error('Server returned an invalid response');
    return data;
  }
  const el = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text != null) node.textContent = text; return node; };
  const relative = value => { if (!value) return 'No moves yet'; const seconds = Math.max(0, (Date.now() - new Date(value).getTime()) / 1000); if (seconds < 60) return 'just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)} min ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)} hr ago`; return `${Math.floor(seconds / 86400)} days ago`; };
  const networkParts = value => {
    const raw = String(value || '').trim();
    const match = raw.match(/^(AS\d+)(?:(?:\s*·\s*|\s+)(.+))?$/i);
    return { raw:raw || null, asn:match?.[1]?.toUpperCase() || null, provider:match?.[2]?.trim() || (match ? null : raw || null) };
  };
  const explicitNetworkType = value => ['isp','hosting','business'].includes(String(value || '').toLowerCase()) ? String(value).charAt(0).toUpperCase()+String(value).slice(1).toLowerCase() : null;
  const shortVisitorId = value => String(value || '').replaceAll('-', '').slice(0, 6).toUpperCase() || '—';
  const referrerText = event => event.referrer ? `${event.referrer_label || event.referrer} · ${event.referrer}` : 'Direct';
  const pathname = raw => { try { return new URL(raw || '/', location.origin).pathname || '/'; } catch { return String(raw || '/').split(/[?#]/, 1)[0] || '/'; } };
  const hasTracking = event => ['ref','utm_source','utm_medium','utm_campaign','utm_content','utm_term'].some(key=>event?.[key]);
  const sourceText = event => { const label=event?.referrer_label && event.referrer_label !== 'Direct' ? event.referrer_label : null; return [...new Set([label,event?.utm_source||event?.source].filter(Boolean))].join(' / ') || 'Direct'; };
  const clipped = value => { const node=el('span','truncate',value || '—');node.title=value || '';return node; };
  const withVersion = (name, version) => `${name || 'Unknown'}${version && version !== 'Unknown' ? ` ${version}` : ''}`;
  const deviceText = event => event?.device_name || event?.device_category || 'Unknown';
  const osText = event => withVersion(event?.operating_system, event?.operating_system_version);
  const browserText = event => withVersion(event?.browser || event?.browser_family, event?.browser_version);
  const trackingBlock = event => { const block=el('dl','tracking-block');[['SOURCE',sourceText(event)],['MEDIUM',event?.utm_medium||'—'],['CAMPAIGN',event?.utm_campaign||'—'],['CONTENT',event?.utm_content||'—'],['TERM',event?.utm_term||'—'],['REF',event?.ref||'—']].forEach(([label,value])=>{block.append(el('dt','',label));const dd=el('dd');dd.append(clipped(value));block.append(dd);});return block; };
  const eventDetails = event => { const details=el('details','event-details');details.append(el('summary','','DETAILS'));const net=networkParts(event.asn_org);const networkType=explicitNetworkType(event.network_type||event.asn_type);const values=[['DEVICE',deviceText(event)],['DEVICE TYPE',event.device_type||event.device_category||'Unknown'],['OS',osText(event)],['BROWSER',browserText(event)],['IP',event.ip||'—'],['LOCATION (APPROX. / IP-DERIVED)',[event.city,event.region,event.country].filter(Boolean).join(', ')||'Unknown'],['ASN',net.asn||'—'],['NETWORK PROVIDER',net.provider||'—'],...(networkType?[['NETWORK TYPE',networkType]]:[]),['RAW NETWORK / ASN',net.raw||'—'],['RAW USER-AGENT',event.user_agent||'—'],['FULL URL / PATH',event.path||'/'],['RAW REFERRER',event.referrer||'—'],['UTM SOURCE',event.utm_source||'—'],['UTM MEDIUM',event.utm_medium||'—'],['UTM CAMPAIGN',event.utm_campaign||'—'],['UTM CONTENT',event.utm_content||'—'],['UTM TERM',event.utm_term||'—'],['REF',event.ref||'—']];const list=el('dl','event-detail-grid');values.forEach(([label,value])=>{list.append(el('dt','',label));const dd=el('dd');dd.append(clipped(value));list.append(dd);});details.append(list);return details; };
  const normalizedPaths = rows => { const counts=new Map();rows.forEach(row=>{const path=pathname(row.path);counts.set(path,(counts.get(path)||0)+Number(row.count));});return [...counts].map(([path,count])=>({path,count})).sort((a,b)=>b.count-a.count||a.path.localeCompare(b.path)); };
  const state = (id, message, error = false) => { const target = document.getElementById(id); target.replaceChildren(el('div', error ? 'error' : 'empty', message)); };

  function metric(label, value) { const node = el('div', 'metric'); node.append(el('b', '', String(value ?? 0)), el('span', '', label)); return node; }
  async function loadOverview() {
    try {
      const { overview: o } = await api('/api/admin/overview');
      const streak = o.current_streak?.count ? `${o.current_streak.count} ${o.current_streak.who === 'jeremy' ? 'W' : 'L'}` : '—';
      document.getElementById('overview-content').replaceChildren(metric('Visitors', o.visitors), metric('Visits', o.total_visits), metric('IPs observed', o.ips_observed), metric('Legacy / unidentified visits', o.unidentified_visits), metric('Visits today', o.visits_today), metric('Challenges created', o.total_challenges), metric('Active matches', o.active_matches), metric('Games played', o.games_completed), metric('Wins', o.jeremy_wins), metric('Losses', o.player_wins), metric('Current streak', streak), metric("Jeremy's move", o.my_turn));
      document.getElementById('updated').textContent = `Updated ${relative(new Date())}`;
    } catch (error) { state('overview-content', `Unable to load overview — ${error.message}`, true); }
  }

  function challengeCard(c, status) {
    const card = el('article', `card${status === 'MY TURN' ? ' urgent' : ''}`); const top = el('div', 'card-top');
    top.append(el('span', `tag${status === 'MY TURN' ? ' turn' : ''}`, status), el('span', 'tag', c.current_game ? `GAME ${c.current_game.game_number} / BEST OF 3` : 'NO ACTIVE GAME'));
    card.append(top, el('h3', '', c.gamertag), el('div', 'score', `Jeremy ${c.jeremy_wins || 0} — ${c.player_wins || 0} Challenger`));
    const foot = el('div', 'card-foot'); foot.append(el('span', '', relative(c.last_move_at)));
    if (c.current_game && c.status !== 'completed') { const link = el('a', 'button', 'OPEN MATCH'); link.href = `/admin/open/${encodeURIComponent(c.id)}`; foot.append(link); }
    card.append(foot); return card;
  }
  function renderChallengeGroup(id, list, emptyMessage, statusFn) { if (!list.length) return state(id, emptyMessage); const wrap = el('div', 'cards'); list.forEach(c => wrap.append(challengeCard(c, statusFn(c)))); document.getElementById(id).replaceChildren(wrap); }
  async function loadChallenges() {
    try {
      const { challenges } = await api('/api/admin/challenges');
      const active = challenges.filter(c => c.status !== 'completed'); const mine = active.filter(c => c.admin_turn); const waiting = active.filter(c => !c.admin_turn); const completed = challenges.filter(c => c.status === 'completed');
      document.getElementById('turn-count').textContent = String(mine.length);
      renderChallengeGroup('myturn-content', mine, 'No matches require your move.', () => 'MY TURN');
      renderChallengeGroup('waiting-content', waiting, 'No matches are waiting for a challenger.', () => 'WAITING');
      renderChallengeGroup('challenges-content', challenges, 'No challenges have been created.', c => c.status === 'completed' ? 'COMPLETED' : c.admin_turn ? 'MY TURN' : 'WAITING');
      renderChallengeGroup('completed-content', completed, 'No completed matches.', () => 'COMPLETED');
    } catch (error) { ['myturn-content','waiting-content','challenges-content','completed-content'].forEach(id => state(id, `Unable to load challenges — ${error.message}`, true)); }
  }

  async function showVisitor(visitorId) {
    const target = document.getElementById('visitor-detail'); target.hidden = false; target.replaceChildren(el('div', 'state', 'Loading visitor details…'));
    try {
      const { visitor:v }=await api(`/api/admin/visitors/${encodeURIComponent(visitorId)}`);const box=el('div','detail visitor-profile');box.append(el('h3','detail-title',`VISITOR / ${shortVisitorId(v.visitor_id)}`),el('p','state','Anonymous first-party browser profile. This does not identify a real person.'));
      const latest=v.latest_device||{};const latestNet=networkParts(latest.asn_org);const latestType=explicitNetworkType(latest.network_type||latest.asn_type);const connection=el('div','connection-summary');[['DEVICE',deviceText(latest)],['DEVICE TYPE',latest.device_type||'Unknown'],['OS',osText(latest)],['BROWSER',browserText(latest)],['IP',latest.ip||'—'],['ASN',latestNet.asn||'—'],['NETWORK PROVIDER',latestNet.provider||'—'],...(latestType?[['NETWORK TYPE',latestType]]:[]),['LOCATION (APPROX. / IP-DERIVED)',[latest.city,latest.region,latest.country].filter(Boolean).join(', ')||'Unknown']].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),clipped(value));connection.append(item);});box.append(el('h3','detail-heading','LATEST DEVICE / CONNECTION'),connection);
      const nav=el('nav','profile-nav');['OVERVIEW','TIMELINE','SESSIONS','PAGES','NETWORK','ACQUISITION','CHALLENGES'].forEach(name=>{const link=el('a','',name);link.href=`#visitor-${name.toLowerCase()}`;nav.append(link);});box.append(nav);
      const heading=(id,title)=>{const h=el('h3','detail-heading',title);h.id=id;return h;};const grid=el('div','detail-grid');const gamertags=(v.associated_gamertags||[]).join(', ')||'Anonymous';[['First seen',new Date(v.first_seen).toLocaleString()],['Last seen',new Date(v.last_seen).toLocaleString()],['Total visits / events',v.total_visits],['Active days',v.active_days],['Sessions',v.session_count],['IPs observed',(v.observed_ips||[]).length],['Associated gamertags',gamertags],['First acquisition source',sourceText(v.acquisition)],['Most recent source',sourceText(v.recent_source)],['Primary device',v.primary_device||'Unknown'],['Primary browser',v.primary_browser||'Unknown']].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),clipped(String(value)));grid.append(item);});box.append(heading('visitor-overview','OVERVIEW'),grid);
      const timeline=el('ul','timeline');let lastDay=null,lastIp=null,lastPlace=null;[...v.recent_visits].reverse().forEach((event,index)=>{const date=new Date(event.created_at);const day=date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});if(day!==lastDay){timeline.append(el('li','timeline-day',day.toUpperCase()));lastDay=day;}const place=[event.city,event.region,event.country].filter(Boolean).join(', ')||'Unknown';if(lastIp&&event.ip&&lastIp!==event.ip){const changed=el('li','ip-change');changed.append(el('time','',date.toLocaleTimeString()),el('b','','IP changed'),el('span','state',`${lastPlace} → ${place} (approx.)`));timeline.append(changed);}const li=el('li');const action=event.event_type==='challenge_created'?`Challenge created as ${gamertags}`:event.event_type==='section_view'?`Viewed ${event.page_name}`:index===0?'First visit':event.event_type==='challenge_opened'?'Opened Challenge':event.event_type==='contact_opened'?'Opened Contact':`Viewed ${event.page_name}`;li.append(el('time','',date.toLocaleTimeString()),el('b','',action),el('span','state',`${sourceText(event)} · ${pathname(event.path)}`));timeline.append(li);if(event.ip){lastIp=event.ip;lastPlace=place;}});box.append(heading('visitor-timeline','TIMELINE'),timeline);
      const sessions=el('div','session-list');[...(v.sessions||[])].reverse().forEach(session=>{const card=el('article','session-card');card.append(el('h4','',`SESSION ${String(session.number).padStart(2,'0')}`),el('p','state',`${new Date(session.first_seen).toLocaleString()}–${new Date(session.last_seen).toLocaleTimeString()} · ${session.duration_minutes} min · ${session.event_count} pages/sections · ${session.ip_count} IPs`));const flow=el('ol','session-flow');let priorIp=null,priorDevice=null;session.events.forEach(event=>{const currentDevice=`${deviceText(event)} / ${browserText(event)}`;if(priorIp&&event.ip&&priorIp!==event.ip)flow.append(el('li','ip-change',`IP CHANGED  ${priorIp} → ${event.ip}`));if(priorDevice&&priorDevice!==currentDevice)flow.append(el('li','device-change',`DEVICE / BROWSER CHANGED  ${priorDevice} → ${currentDevice}`));flow.append(el('li','',`${new Date(event.created_at).toLocaleTimeString()}  ${event.page_name} · ${currentDevice}${event.ip?' · '+event.ip:''}`));if(event.ip)priorIp=event.ip;priorDevice=currentDevice;});card.append(flow);sessions.append(card);});box.append(heading('visitor-sessions','SESSIONS'),sessions);
      const pages=el('div','profile-columns');const most=el('ul','aggregate-list');(v.page_summary?.pages||[]).forEach(item=>{const li=el('li');li.append(el('span','',item.name),el('b','',item.count));most.append(li);});const pageStats=el('div','detail-grid');[['First section',v.page_summary?.first_section||'—'],['Last section',v.page_summary?.last_section||'—'],['Most viewed',v.page_summary?.most_viewed||'—'],['Challenge visits',v.page_summary?.challenge_visits||0],['Contact visits',v.page_summary?.contact_visits||0]].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),el('span','',value));pageStats.append(item);});pages.append(most,pageStats);box.append(heading('visitor-pages','PAGES / SECTIONS'),pages);
      const activity=el('table','history-table compact-history');const ah=el('tr');['TIMESTAMP','PAGE / SECTION','PATH','SOURCE','ATTRIBUTION','IP','LOCATION (APPROX.)','ASN','NETWORK PROVIDER','DEVICE','TYPE','OS','BROWSER',''].forEach(x=>ah.append(el('th','',x)));const ab=el('tbody');v.recent_visits.forEach(event=>{const row=el('tr');const location=[event.city,event.region,event.country].filter(Boolean).join(', ')||'Unknown';const net=networkParts(event.asn_org);[new Date(event.created_at).toLocaleString(),event.page_name,pathname(event.path),sourceText(event),[event.utm_content,event.ref].filter(Boolean).join(' · ')||'—',event.ip||'—',location,net.asn||'—',net.provider||'—',deviceText(event),event.device_type||event.device_category||'Unknown',osText(event),browserText(event)].forEach(value=>{const cell=el('td');cell.append(clipped(value));row.append(cell);});const dc=el('td');dc.append(eventDetails(event));row.append(dc);ab.append(row);});activity.append(el('thead','').appendChild(ah).parentNode,ab);box.append(heading('visitor-page-activity','PAGE ACTIVITY'),activity);
      const ips=el('div','network-cards');(v.observed_ips||[]).forEach(item=>{const card=el('article','session-card');const link=el('button','text-link',item.ip);const net=networkParts(item.asn_org);link.addEventListener('click',()=>{document.getElementById('ips').scrollIntoView();showIp(item.ip);});card.append(link,el('p','',`${[item.city,item.region,item.country].filter(Boolean).join(', ')||'Unknown'} (approx.)`),el('p','state',`ASN ${net.asn||'—'} · PROVIDER ${net.provider||'—'}`),el('p','state',`${new Date(item.first_seen).toLocaleString()}–${new Date(item.last_seen).toLocaleString()}`));ips.append(card);});box.append(heading('visitor-network','NETWORK HISTORY'),ips);
      const a=v.acquisition;box.append(heading('visitor-acquisition','FIRST ACQUISITION'),...(hasTracking(a)?[trackingBlock(a)]:[]));const acquisition=el('div','detail-grid');[['Raw referrer',a?.referrer||'—'],['Landing page',a?pathname(a.path):'—'],['First seen',a?.created_at?new Date(a.created_at).toLocaleString():'—']].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),clipped(value));acquisition.append(item);});box.append(acquisition);
      const c=v.challenge_activity;const challengeGrid=el('div','detail-grid');[['Gamertag',gamertags],['Challenges created',c.challenges_created],['Games completed',c.games_completed],['Current active challenge',c.current_active?'Yes':'No'],['Last challenge activity',c.last_activity?new Date(c.last_activity).toLocaleString():'—'],['Jeremy / Challenger wins',`${c.jeremy_wins} / ${c.challenger_wins}`]].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),el('span','',value));challengeGrid.append(item);});box.append(heading('visitor-challenges','CHALLENGE ACTIVITY'),challengeGrid,el('p','state','Gamertags appear only when explicitly associated through this Visitor ID.'));target.replaceChildren(box);target.scrollIntoView({block:'start'});
    } catch (error) { target.replaceChildren(el('div','error',`Unable to load visitor — ${error.message}`)); }
  }
  async function loadVisitors(page = visitorPage) {
    visitorPage = page;
    try {
      const { visitors, pagination } = await api(`/api/admin/visitors?page=${page}&page_size=25`); if (!visitors.length) { state('visitors-content','No visitor data yet.'); return; }
      const table = el('table'); const head = el('thead'); const hr = el('tr'); ['VISITOR','GAMERTAG','IP COUNT','RECENT IP','COUNTRY','REGION','CITY','ASN','NETWORK PROVIDER','DEVICE','VISITS','LAST SEEN'].forEach(x => hr.append(el('th','',x))); head.append(hr); const body = el('tbody');
      visitors.forEach(v => { const row = el('tr'); const gamertags=(v.associated_gamertags || []).join(', ') || '—';const net=networkParts(v.asn_org); [[shortVisitorId(v.visitor_id),''],[gamertags,''],[v.ip_count,''],[v.most_recent_ip || '—',''],[v.country || 'Unknown','hide-mobile'],[v.region || 'Unknown','hide-mobile'],[v.city || 'Unknown','hide-mobile'],[net.asn||'—','hide-mobile'],[net.provider||'—','hide-mobile'],[v.device_name || v.device_category || 'Unknown','hide-mobile'],[v.visits,''],[relative(v.last_seen),'']].forEach(([value,className]) => row.append(el('td',className,value))); row.addEventListener('click',()=>showVisitor(v.visitor_id)); body.append(row); }); table.append(head,body); document.getElementById('visitors-content').replaceChildren(table);
      const pager = document.getElementById('visitor-pagination'); pager.replaceChildren(); if (pagination.page > 1) { const prev = el('button','','← PREV'); prev.addEventListener('click',()=>loadVisitors(page-1)); pager.append(prev); } pager.append(el('span','state',`PAGE ${pagination.page} / ${Math.max(1,pagination.pages)}`)); if (pagination.page < pagination.pages) { const next = el('button','','NEXT →'); next.addEventListener('click',()=>loadVisitors(page+1)); pager.append(next); }
    } catch (error) { state('visitors-content',`Unable to load visitors — ${error.message}`,true); }
  }
  let ipPage = 1;
  async function showIp(ip, historyPage = 1) {
    const target = document.getElementById('ip-detail'); target.hidden = false; target.replaceChildren(el('div','state','Loading IP details…'));
    try {
      const { ip: detail, pagination } = await api(`/api/admin/ips/${encodeURIComponent(ip)}?page=${historyPage}&page_size=25`); const box=el('div','detail');
      const back=el('button','','← BACK TO IPS'); back.addEventListener('click',()=>{ target.hidden=true; target.replaceChildren(); document.getElementById('ips-content').scrollIntoView(); });
      box.append(back,el('h3','detail-title',`IP ${detail.address}`),el('p','state','An IP is a network address, not a human visitor. One IP may be used by multiple Visitor IDs. Geolocation below is approximate and is not the visitor’s physical location.'));
      const section = title => el('h3','detail-heading',title);
      const grid=el('div','detail-grid'); [['IP address',detail.address],['First seen',new Date(detail.first_seen).toLocaleString()],['Last seen',new Date(detail.last_seen).toLocaleString()],['Total visits / events',detail.total_visits],['Distinct Visitor IDs',detail.distinct_visitor_ids],['Associated gamertags',(detail.associated_gamertags||[]).join(', ')||'—'],['Devices',(detail.device_names||detail.device_categories||[]).join(', ')||'Unknown'],['Operating systems',(detail.operating_systems||[]).join(', ')||'Unknown'],['Browsers',(detail.browsers||[]).join(', ')||'Unknown']].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),el('span','',value));grid.append(item);});
      const detailNet=networkParts(detail.asn_org);const detailType=explicitNetworkType(detail.network_type||detail.asn_type);const location=el('div','detail-grid'); [['IP',detail.address],['ASN',detailNet.asn||'—'],['Network Provider',detailNet.provider||'—'],...(detailType?[['Network Type',detailType]]:[]),['Country (approx.)',detail.country||'Unknown'],['Region (approx.)',detail.region||'Unknown'],['City (approx.)',detail.city||'Unknown'],['Timezone',detail.timezone||'Unknown']].forEach(([label,value])=>{const item=el('div');item.append(el('label','',label),el('span','',value));location.append(item);});
      const visitorTable=el('table'); const vh=el('tr'); ['VISITOR ID','FIRST SEEN FROM IP','LAST SEEN FROM IP','EVENTS','GAMERTAGS'].forEach(x=>vh.append(el('th','',x))); const vb=el('tbody'); (detail.visitors||[]).forEach(v=>{const row=el('tr'); const link=el('button','text-link',shortVisitorId(v.visitor_id)); link.title=v.visitor_id; link.addEventListener('click',()=>{document.getElementById('visitors').scrollIntoView();showVisitor(v.visitor_id);}); const first=el('td');first.append(link);row.append(first,el('td','',new Date(v.first_seen).toLocaleString()),el('td','',new Date(v.last_seen).toLocaleString()),el('td','',v.visits),el('td','',(v.associated_gamertags||[]).join(', ')||'—'));vb.append(row);}); if(detail.legacy_events){const row=el('tr');row.append(el('td','','Legacy / unidentified'),el('td','',new Date(detail.legacy_first_seen).toLocaleString()),el('td','',new Date(detail.legacy_last_seen).toLocaleString()),el('td','',detail.legacy_events),el('td','','—'));vb.append(row);} visitorTable.append(el('thead','').appendChild(vh).parentNode,vb);
      const aggregateTable=(heading,rows,labelKey)=>{const wrap=el('div');wrap.append(section(heading));const list=el('ul','aggregate-list');rows.forEach(row=>{const li=el('li');li.append(el('span','',row[labelKey]),el('b','',row.count));list.append(li);});wrap.append(list);return wrap;};
      const history=el('table','history-table compact-history'); const hh=el('tr'); ['TIMESTAMP','VISITOR ID','GAMERTAG','PATH','SOURCE','MEDIUM','REF','DEVICE','TYPE','OS','BROWSER','LOCATION (APPROX.)','ASN','NETWORK PROVIDER',''].forEach(x=>hh.append(el('th','',x))); const hb=el('tbody'); detail.events.forEach(event=>{const row=el('tr');const visitorCell=el('td');if(event.visitor_id){const link=el('button','text-link',shortVisitorId(event.visitor_id));link.title=event.visitor_id;link.addEventListener('click',()=>{document.getElementById('visitors').scrollIntoView();showVisitor(event.visitor_id);});visitorCell.append(link);}else visitorCell.textContent='Legacy / unidentified';const location=[event.city,event.region,event.country].filter(Boolean).join(', ')||'Unknown';const net=networkParts(event.asn_org);const cells=[new Date(event.created_at).toLocaleString(),visitorCell,(event.associated_gamertags||[]).join(', ')||'—',pathname(event.path),sourceText(event),event.utm_medium||'—',event.ref||'—',deviceText(event),event.device_type||event.device_category||'Unknown',osText(event),browserText(event),location,net.asn||'—',net.provider||'—'];cells.forEach((value,index)=>{if(index===1)row.append(value);else{const cell=el('td');cell.append(clipped(value));row.append(cell);}});const detailCell=el('td');detailCell.append(eventDetails(event));row.append(detailCell);hb.append(row);});history.append(el('thead','').appendChild(hh).parentNode,hb);
      const historyPager=el('div','pagination');if(pagination.page>1){const prev=el('button','','← NEWER');prev.addEventListener('click',()=>showIp(ip,historyPage-1));historyPager.append(prev);}historyPager.append(el('span','state',`PAGE ${pagination.page} / ${Math.max(1,pagination.pages)}`));if(pagination.page<pagination.pages){const next=el('button','','OLDER →');next.addEventListener('click',()=>showIp(ip,historyPage+1));historyPager.append(next);}
      const trackedEvent=detail.events.find(hasTracking);box.append(section('SUMMARY'),grid,section('NETWORK / APPROXIMATE LOCATION'),location,section('VISITOR IDs USING THIS IP'),visitorTable,aggregateTable('REFERRERS',detail.referrers,'source'),...(trackedEvent?[section('TRACKING SUMMARY'),trackingBlock(trackedEvent)]:[]),aggregateTable('PATHS',normalizedPaths(detail.paths),'path'),section('VISIT HISTORY'),history,historyPager); target.replaceChildren(box); target.scrollIntoView({block:'start'});
    }
    catch(error){ target.replaceChildren(el('div','error',`Unable to load IP — ${error.message}`)); }
  }
  async function loadIps(page = ipPage) {
    ipPage=page;
    try { const { ips, pagination }=await api(`/api/admin/ips?page=${page}&page_size=25`); if(!ips.length){state('ips-content','No IP data yet.');return;} const table = el('table'); const head=el('thead'); const hr=el('tr'); ['IP','IP-ASSOCIATED GAMERTAGS','COUNTRY','REGION','CITY','ASN','NETWORK PROVIDER','VISITS','LAST SEEN'].forEach(x=>hr.append(el('th','',x))); head.append(hr); const body=el('tbody'); ips.forEach(item=>{const row=el('tr'); const ipCell=el('td');const link=el('button','text-link',item.ip);const net=networkParts(item.asn_org);link.addEventListener('click',()=>showIp(item.ip));ipCell.append(link);row.append(ipCell); [[(item.ip_associated_gamertags||[]).join(', ')||'—',''],[item.country||'Unknown','hide-mobile'],[item.region||'Unknown','hide-mobile'],[item.city||'Unknown','hide-mobile'],[net.asn||'—','hide-mobile'],[net.provider||'—','hide-mobile'],[item.visits,''],[relative(item.last_seen),'']].forEach(([value,className])=>row.append(el('td',className,value))); body.append(row);}); table.append(head,body); document.getElementById('ips-content').replaceChildren(table); const pager=document.getElementById('ip-pagination'); pager.replaceChildren(); if(pagination.page>1){const prev=el('button','','← PREV');prev.addEventListener('click',()=>loadIps(page-1));pager.append(prev);} pager.append(el('span','state',`PAGE ${pagination.page} / ${Math.max(1,pagination.pages)}`)); if(pagination.page<pagination.pages){const next=el('button','','NEXT →');next.addEventListener('click',()=>loadIps(page+1));pager.append(next);} }
    catch(error){state('ips-content',`Unable to load IPs — ${error.message}`,true);}
  }
  let trackingPage=1;
  async function showTracking(ref, page=1) {
    const target=document.getElementById('tracking-detail');target.hidden=false;target.replaceChildren(el('div','state','Loading referral details…'));
    try { const { referral, pagination }=await api(`/api/admin/tracking/${encodeURIComponent(ref)}?page=${page}&page_size=25`);const box=el('div','detail');box.append(el('h3','detail-title',`REF ${ref}`),el('p','state','Visitor IDs and IPs are analytics attributes, not proof of a real person’s identity.'));
      const visitors=el('table');const vh=el('tr');['VISITOR ID','EVENTS','FIRST SEEN','LAST SEEN'].forEach(x=>vh.append(el('th','',x)));const vb=el('tbody');referral.visitors.forEach(v=>{const row=el('tr');const cell=el('td');const link=el('button','text-link',shortVisitorId(v.visitor_id));link.title=v.visitor_id;link.addEventListener('click',()=>{document.getElementById('visitors').scrollIntoView();showVisitor(v.visitor_id);});cell.append(link);row.append(cell,el('td','',v.visits),el('td','',new Date(v.first_seen).toLocaleString()),el('td','',new Date(v.last_seen).toLocaleString()));vb.append(row);});visitors.append(el('thead','').appendChild(vh).parentNode,vb);
      const events=el('table','history-table compact-history');const eh=el('tr');['TIMESTAMP','VISITOR ID','IP','PATH','SOURCE','MEDIUM','REF',''].forEach(x=>eh.append(el('th','',x)));const eb=el('tbody');referral.events.forEach(event=>{const row=el('tr');[new Date(event.created_at).toLocaleString(),event.visitor_id?shortVisitorId(event.visitor_id):'Legacy / unidentified',event.ip||'—',pathname(event.path),sourceText(event),event.utm_medium||'—',event.ref||'—'].forEach(value=>{const cell=el('td');cell.append(clipped(value));row.append(cell);});const detailCell=el('td');detailCell.append(eventDetails(event));row.append(detailCell);eb.append(row);});events.append(el('thead','').appendChild(eh).parentNode,eb);const pager=el('div','pagination');if(page>1){const prev=el('button','','← NEWER');prev.addEventListener('click',()=>showTracking(ref,page-1));pager.append(prev);}pager.append(el('span','state',`PAGE ${pagination.page} / ${Math.max(1,pagination.pages)}`));if(page<pagination.pages){const next=el('button','','OLDER →');next.addEventListener('click',()=>showTracking(ref,page+1));pager.append(next);}box.append(...(referral.events.some(hasTracking)?[el('h3','detail-heading','TRACKING SUMMARY'),trackingBlock(referral.events.find(hasTracking))]:[]),el('h3','detail-heading','ASSOCIATED VISITOR IDs'),visitors,el('h3','detail-heading','EVENT HISTORY'),events,pager);target.replaceChildren(box);target.scrollIntoView({block:'start'});
    } catch(error){target.replaceChildren(el('div','error',`Unable to load referral — ${error.message}`));}
  }
  async function loadTracking(page=trackingPage){trackingPage=page;try{const { tracking,pagination }=await api(`/api/admin/tracking?page=${page}&page_size=25`);if(!tracking.length){state('tracking-content','No tracked links recorded yet.');return;}const table=el('table');const head=el('tr');['REF','SOURCE','MEDIUM','CAMPAIGN','VISITS / EVENTS','VISITOR IDS','FIRST SEEN','LAST SEEN'].forEach(x=>head.append(el('th','',x)));const body=el('tbody');tracking.forEach(item=>{const row=el('tr');const refCell=el('td');if(item.ref){const link=el('button','text-link truncate',item.ref);link.title=item.ref;link.addEventListener('click',()=>showTracking(item.ref));refCell.append(link);}else refCell.textContent='—';row.append(refCell);[item.source||'—',item.medium||'—',item.campaign||'—'].forEach(value=>{const cell=el('td');cell.append(clipped(value));row.append(cell);});row.append(el('td','',item.visits),el('td','',item.distinct_visitor_ids),el('td','',new Date(item.first_seen).toLocaleString()),el('td','',new Date(item.last_seen).toLocaleString()));body.append(row);});table.append(el('thead','').appendChild(head).parentNode,body);document.getElementById('tracking-content').replaceChildren(table);const pager=document.getElementById('tracking-pagination');pager.replaceChildren();if(page>1){const prev=el('button','','← PREV');prev.addEventListener('click',()=>loadTracking(page-1));pager.append(prev);}pager.append(el('span','state',`PAGE ${pagination.page} / ${Math.max(1,pagination.pages)}`));if(page<pagination.pages){const next=el('button','','NEXT →');next.addEventListener('click',()=>loadTracking(page+1));pager.append(next);}}catch(error){state('tracking-content',`Unable to load tracking — ${error.message}`,true);}}
  async function refresh() { document.getElementById('refresh').disabled = true; await Promise.allSettled([loadOverview(),loadChallenges(),loadVisitors(visitorPage),loadIps(ipPage),loadTracking(trackingPage)]); document.getElementById('refresh').disabled = false; }
  document.getElementById('refresh').addEventListener('click',refresh);
  document.getElementById('logout').addEventListener('click',async()=>{ try { await api('/admin/logout',{method:'POST',headers:{'x-csrf-token':csrf}}); location.reload(); } catch (error) { alert(`Unable to log out — ${error.message}`); } });
  refresh(); setInterval(() => { loadOverview(); loadChallenges(); }, 30000);
})();
